language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

env:
  - CENTOS_VERSION=7.7.1908

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --pull -t alvisisme/centos:$CENTOS_VERSION -f $CENTOS_VERSION/Dockerfile $CENTOS_VERSION
  - docker push alvisisme/centos:$CENTOS_VERSION
